AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  daily_encouragement

  SAM Template for daily_encouragement

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Mappings:
  common:
    { your_region }:
      arnlayeropenai: { arn_for_lambda_layer }

Resources:
  DailyEncouragementFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers: # openAI layer arn
        - !FindInMap [common, !Ref AWS::Region, arnlayeropenai]
      Architectures:
        - x86_64
      Events:
        DailyEncouragementEvent:
          Type: SNS
          Properties:
            Topic: !Ref DailyEncouragementSNSTopic
        DailyEncouragementApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  DailyEncouragementSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: DailyEncouragementSNSTopic
      DisplayName: daily-encouragement-sns-topic

  LambdaSNSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt DailyEncouragementFunction.Arn
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref DailyEncouragementSNSTopic

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: true
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  DailyEncouragementFunction:
    Description: DailyEncouragementFunction Lambda Function ARN
    Value: !GetAtt DailyEncouragementFunction.Arn
  DailyEncouragementFunctionIamRole:
    Description: Implicit IAM Role created for DailyEncouragementFunction function
    Value: !GetAtt DailyEncouragementFunctionRole.Arn
